---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(tidyverse)
library(rvest)
```

## Data 

```{r}
masters <- read_csv("Data/Master.csv")
coaches <- read_csv("Data/Coaches.csv")
awardCoaches <- read_csv("Data/AwardsCoaches.csv")
teams <- read_csv("Data/Teams.csv")
teamsPost <- read_csv("Data/TeamsPost.csv")

wiki <- read_html("https://en.wikipedia.org/wiki/List_of_Stanley_Cup_champions")

SC <- html_nodes(wiki, css = "table")

sc_data <- html_table(SC, header = T, fill = T)[[3]]
                 
```

#Tanush
```{r}
#selecting NHL
teams_F <- teams %>% filter(lgID == "NHL")

teams_F %>% filter(tmID=="MTL" | tmID=="LAK" | tmID=="BOS") %>% ggplot(aes(year, W)) + geom_point(aes(color=tmID)) + geom_line(aes(color=tmID), alpha =0.6) + labs(y="Wins")
```

#Zach
```{r}
awardCoaches2 <- awardCoaches %>% 
  filter(award == "Jack Adams") %>% 
  select(-note)

masters_names <- masters %>% 
  select(coachID, firstName, lastName)

awardCoaches_f <- left_join(awardCoaches2, masters_names)
```


#Pete

```{r}
coaches1 = coaches %>% 
  filter(lgID == "NHL") %>% 
  group_by(coachID) %>% 
  summarise(number_of_years_in_league = (1+max(year)-min(year)))

coaches2 = coaches %>% 
  filter(lgID == "NHL") %>% 
  group_by(coachID) %>% 
  summarise(reg_overall_win = sum(w), reg_overall_loss = sum(l), reg_overall_tie = sum(t), reg_num_game = sum(g))

coaches3 = coaches %>% 
  filter(lgID == "NHL") %>% 
  group_by(coachID) %>% 
  summarise(post_overall_win = sum(postw), post_overall_loss = sum(postl), post_overall_tie = sum(postt), post_num_game = sum(postg))

coaches4 = coaches1 %>% 
  full_join(coaches2, by = "coachID") %>%
  full_join(coaches3, by = "coachID")

coaches_f = coaches4 %>% 
  mutate(reg_win_percent = (reg_overall_win/reg_num_game), post_win_percent = post_overall_win/post_num_game) %>% 
  select(coachID:reg_overall_tie, reg_win_percent, post_overall_win:post_overall_tie,post_win_percent)

coaches = coaches %>% filter(lgID == "NHL")
  
```

